import React, { useEffect } from 'react';
import { ChevronLeft } from 'lucide-react';

const TermsOfServicePage = ({ setCurrentPage }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen pt-28 pb-20 px-4 sm:px-6 lg:px-8 max-w-3xl mx-auto font-sans text-zinc-300">
      <button onClick={() => setCurrentPage('home')} className="flex items-center gap-2 text-zinc-500 hover:text-cyan-400 font-sans text-[10px] uppercase tracking-widest mb-8 transition-colors">
        <ChevronLeft size={14} /> Back to Home
      </button>

      <h1 className="text-3xl md:text-5xl font-black italic uppercase tracking-tight text-white mb-2">Terms of Service</h1>
      <p className="text-zinc-500 font-sans text-xs uppercase tracking-widest mb-10">Last Updated: April 5, 2026</p>

      <div className="space-y-10">
        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">1. Introduction and Merchant of Record</h2>
          <p className="leading-relaxed text-sm">
            These Terms of Service ("Terms") govern your access to and use of the mogcheck website and services ("Service"). Our order process is conducted by our Merchant of Record, Paddle.com Market Limited ("Paddle"). Paddle is the specialist responsible for all customer service inquiries and returns. By using the Service, you agree to be bound by these Terms and Paddle’s Buyer Terms available at <a href="https://paddle.com/legal" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:text-cyan-300 transition-colors">paddle.com/legal</a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">2. Nature of the Service</h2>
          <p className="leading-relaxed text-sm mb-4">
            mogcheck is an automated software utility that uses computer vision and artificial intelligence to analyze facial proportions, symmetry, and aesthetic geometry.
          </p>
          <ul className="list-disc pl-5 space-y-3 text-sm">
            <li><strong className="text-zinc-100">Educational & Entertainment Use Only:</strong> The Service is provided solely for educational and entertainment purposes.</li>
            <li><strong className="text-zinc-100">No Medical Advice:</strong> The results generated by the Service do not constitute medical, clinical, dermatological, or surgical advice or diagnosis.</li>
            <li><strong className="text-zinc-100">Subjectivity Disclaimer:</strong> Aesthetic analysis is based on mathematical models of classical proportions. These results are subjective and do not define an individual's objective value or attractiveness.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">3. Eligibility and User Conduct</h2>
          <p className="leading-relaxed text-sm mb-4">
            By using mogcheck, you represent and warrant that:
          </p>
          <ul className="list-disc pl-5 space-y-3 text-sm">
            <li>You are at least 18 years of age.</li>
            <li>You are uploading a photo of yourself or have obtained express, documented consent from the individual pictured.</li>
            <li>You will not use the Service for any illegal, harmful, or predatory purposes, including stalking or unauthorized biometric profiling of third parties.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">4. Fees and No-Refund Policy</h2>
          <ul className="list-disc pl-5 space-y-3 text-sm">
            <li><strong className="text-zinc-100">Pricing:</strong> We offer a $8.00 One-Time Report and a $20.00 Monthly Subscription.</li>
            <li><strong className="text-zinc-100">Immediate Performance:</strong> By purchasing a report or subscription, you expressly request that the Service begins immediately.</li>
            <li><strong className="text-zinc-100">No Refunds:</strong> Due to the digital nature of the product and the immediate delivery of value (AI analysis), all sales are final and non-refundable.</li>
            <li><strong className="text-zinc-100">Waiver of Withdrawal:</strong> You acknowledge that you lose your statutory right of withdrawal (including under EU/UK consumer law) once the AI analysis has been generated for your account.</li>
            <li><strong className="text-zinc-100">Subscriptions:</strong> You may cancel your $20.00 Monthly Subscription at any time to prevent future billing. No pro-rata refunds are provided for the remaining days of a billing cycle already in progress.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">5. Data Privacy and Biometrics</h2>
          <ul className="list-disc pl-5 space-y-3 text-sm">
            <li><strong className="text-zinc-100">Analysis vs. Identification:</strong> mogcheck performs Landmark Detection to measure distances and ratios. We do not perform "Facial Recognition" for the purpose of identifying individuals.</li>
            <li><strong className="text-zinc-100">Non-Retention Policy:</strong> Images uploaded to mogcheck are processed in transient memory and are deleted immediately upon the completion of the analysis report. We do not maintain a persistent database of user faces.</li>
            <li><strong className="text-zinc-100">Third-Party APIs:</strong> You acknowledge that data may be processed via secure third-party AI infrastructure (e.g., Google Gemini, OpenAI) to generate your report.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">6. Intellectual Property</h2>
          <ul className="list-disc pl-5 space-y-3 text-sm">
            <li><strong className="text-zinc-100">Our Property:</strong> The mogcheck name, logo, AI algorithms, "Engine" logic, and report formats are the exclusive intellectual property of the Service.</li>
            <li><strong className="text-zinc-100">Your License:</strong> You are granted a limited, non-exclusive license to use the Service and download your generated reports for personal, non-commercial use.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">7. Limitation of Liability</h2>
          <p className="leading-relaxed text-sm">
            To the maximum extent permitted by law, mogcheck and its developers shall not be liable for any indirect, incidental, or consequential damages (including, but not limited to, emotional distress or loss of data) arising from your use of the Service or your interpretation of the AI-generated results. You use this Service at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">8. Account Termination</h2>
          <p className="leading-relaxed text-sm">
            We reserve the right to suspend or terminate your access to the Service without notice if we believe you have violated these Terms, engaged in fraudulent activity, or used the Service for unauthorized biometric surveillance.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">9. Governing Law</h2>
          <p className="leading-relaxed text-sm">
            These Terms shall be governed by and construed in accordance with the laws of Malaysia. Any legal action or proceeding arising under these Terms will be brought exclusively in the courts of Malaysia.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-black uppercase tracking-widest text-white mb-4">10. Contact Information</h2>
          <p className="leading-relaxed text-sm">
            For support or questions regarding these Terms, please contact us at:<br/>
            Email: <a href="mailto:support@mogcheck.com" className="text-cyan-400 hover:text-cyan-300 transition-colors">support@mogcheck.com</a>
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfServicePage;